config/routes.rb
Rails.application.routes.draw do

  
  scope '/board' do
    resources :posts do
      resources :comments
    end
  end
  
  get 'board' => 'board#index'

  devise_for :users , controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  get 'home/index'

  get 'board/index'
  

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :posts
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  before_action :set_post, only: [:show_post, :edit_post, :update_post, :destroy_post]
  before_action :set_comment, only: [:edit_comment, :update_comment, :destroy_comment]
  before_filter :authenticate_user!

  def index
    @posts = Post.all
  end
  
  def new_post
    @post = Post.new
  end
  
  def create_post
  end
  
  def show_post
  end
  
  def edit_post
  end
  
  def update_post
  end

  def destroy_post
  end
  
  def new_comment
  end
  
  def create_comment
  end
  
  def edit_comment
  end
  
  def update_comment
  end
  
  def destroy_comment
  end
  
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def post_params
    #   params.require(:post).permit(:title, :description)
    # end
    
    def post_params
      params.require(:post).permit(:category, :title, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
      before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    # @post = Post.new
  end

  # GET /posts/1/edit
  def edits
  end

  # POST /posts
  # POST /posts.json
  def create

    @post = Post.new(post_params)
    @post.user = current_user
      respond_to do |format|
      if @post.save
        format.html { redirect_to '/board/posts', notice: '게시물이 성공적으로 등록되었습니다.' }
        # format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        # format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        # format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        # format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def post_params
    #   params.require(:post).permit(:title, :description)
    # end
    
    def post_params
      params.require(:post).permit(:category, :title, :content)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/board/index.html.erb
<br><br><br>

<a href="/board/posts/new">post생성</a>
<% if @posts.present?%>
    <%@posts.each do |post| %>
        <h4><%=post.title%></h4>
        <h4><%=post.user%></h4>
        <br>
        <h5><%=post.content%></h5>
    <% end%>
<% else %>
    <h4>게시글이 없습니다</h4>
<%end %>

app/views/home/index.html.erb
        <section id="home" class="home">
            <div class="home_overlay">
                <div class="container">
                    <div class="row">
						
						<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
						  <!-- Indicators -->
						 

						  <!-- Wrapper for slides -->
						<div class="carousel-inner" role="listbox">
							<div class="item active">
								 <div class="carousel-caption">
									<p>Women of Virtue</p>
									<div class="btn_bg">
										<% if user_signed_in? %>
											<%=link_to "LOG IN", new_user_session_path, {class: "btn"} %>
											<br><br><br><br>
											<%#=link_to "SIGN IN", new_user_registration_path, {class: "btn"} %>
										<% else %>
											<%=link_to "LOG OUT", destroy_user_session_path, {class: "btn"} %>
										<% end %>
										<!--<a href="" class="btn ">LOG IN</a>-->
									</div>
								</div>
								<img src="assets/images/slider.jpg" alt="...">
							</div>
							<!--<div class="item">-->
							<!--	<div class="carousel-caption">-->
							<!--		<p></p><br><br><br>-->
							<!--		<div class="btn_bg">-->
							<!--			<a href="" class="btn ">LOG-IN</a>-->
							<!--		</div>-->
							<!--	</div>-->
							<!--	<img src="assets/images/slider.jpg" alt="...">-->
							<!--</div>-->
							<!--<div class="item">-->
							<!--	<div class="carousel-caption">-->
							<!--		<p></p><br><br><br>-->
							<!--		<div class="btn_bg">-->
							<!--			<a href="" class="btn ">POSTSCRIPTS</a>-->
							<!--		</div>-->
							<!--	</div>-->
							<!--	<img src="assets/images/slider.jpg" alt="...">-->
							<!--</div>-->
						</div>


						</div>						
						
						
						
						
						
						
						
						
						
						
						<div class="scrolldown">
							<a href="#whatido" class="scroll_btn"></a>
						</div>
						
						
                    </div>
                </div>
            </div>
        </section><!-- End of Banner Section -->


        

        <section id="whatido" class="whatido">
            <div class="container">
                <div class="row">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="head_title text-center wow fadeInLeft"  data-wow-duration="3s">
							<h2>ABOUT</h2>
							<div class="separator"></div>
						</div>
					</div>
					
					<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="head_title_rigth wow fadeInRight"  data-wow-duration="3s">
							<p>왜 여성의 자위는 조용해야 하는가? 왜 여성의 자위는 창피해야 하는가? 'Women of Virtue'는 다양한 자위 방법을 알려주고, 개인적인 자위 고민을 해결해주고, 자위 및 기구 후기에 대한 정보를 공유합니다. 여러분들의 당당한 자기위로 시간을 응원합니다!</p>
						</div>
					</div><!-- End of col-sm-5 -->
                    <div class="main_whatido_content text-center">
						<div class="col-md-4 col-sm-6 col-xs-12">
							<div class="single_whatido wow fadeInDown"  data-wow-duration="1s">
								<div class="single_whatido_img">
									<img src="assets/images/1-2.png" alt="" />
								</div>
								<h3>자신있게!</h3>
								<p>자신있게 자위하기!</p>
							</div>
						</div>
						
						<div class="col-md-4 col-sm-6 col-xs-12">
							<div class="single_whatido wow fadeInDown"  data-wow-duration="3s">
								<div class="single_whatido_img">
									<img src="assets/images/1-1.png" alt="" />
								</div>
								<h3>건강하게!</h3>
								<p>건강하게 자위하기!</p>
							</div>
						</div>
						
						<div class="col-md-4 col-sm-6 col-xs-12">
							<div class="single_whatido wow fadeInDown"  data-wow-duration="4s">
								<div class="single_whatido_img">
									<img src="assets/images/1-3.jpg" alt="" />
								</div>
								<h3>쾌감있게!</h3>
								<p>충분하고 여유롭게 최고의 절정을 누려라!</p>
							</div>
						</div>
                    </div>
                </div>
            </div>
        </section><!-- End of Features Section -->

        <section id="myworks" class="myworks">
            <div class="container">
                <div class="row">	
					<div class="col-md-1 col-md-offset-5 col-sm-1 col-sm-offset-5 col-xs-12 no-padding">
						<div class="scrolldownall text-right">
							<a href="#about" class="scroll_btnall"></a>
						</div>
					</div><!-- End of col-sm-2 -->
					<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="head_title text-center wow fadeInLeft"  data-wow-duration="2s">
							<h2>HOW TO MASTURBATION</h2>
							<div class="separator"></div>
						</div>
					</div>
					
                </div>
            </div>
			
			<div class="main_myworks_content text-center">
				<div class="single_work_colum col-md-3 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="1.5s">
					<div class="single_work">
						<img src="assets/images/6.png" alt="" />
					</div>
				</div>
				<div class="single_work_colum col-md-3 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="2s">
					<div class="single_work">
						<img src="assets/images/4.png" alt="" />
					</div>
				</div>
				<div class="single_work_colum col-md-3 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="3s">
					<div class="single_work">
						<img src="assets/images/5.png" alt="" />
					</div>
				</div>
				<div class="single_work_colum col-md-3 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="4s">
					<div class="single_work">
						<img src="assets/images/10.png" alt="" />
					</div>
				</div>
				
				<div class="btn_bg wow fadeInLeft"  data-wow-duration="3s">
				<a href="/" class="btn">load More</a>
				</div>
			</div>
        </section><!-- End of Features Section -->
        
        <!--<section id="myworks" class="myworks">-->
        <section id="about" class="about">
            <div class="container">
                <div class="row">	
					<div class="col-md-1 col-md-offset-5 col-sm-1 col-sm-offset-5 col-xs-12 no-padding">
						<div class="scrolldownall text-right">
							<a href="#about" class="scroll_btnall"></a>
						</div>
					</div><!-- End of col-sm-2 -->
					<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="head_title text-center wow fadeInLeft"  data-wow-duration="2s">
							<h2>POSTSCRIPTS</h2>
							<div class="separator"></div>
						</div>
					</div>
					
                </div>
            </div>
			
			<div class="main_myworks_content text-center">
				<div class="single_work_colum col-md-3 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="1.5s">
					<div class="single_work">
						<img src="assets/images/11.JPG" alt="" />
					</div>
					<p>개추천!! 짱 좋아요</p>
				</div>
				<div class="single_work_colum col-md-3 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="2s">
					<div class="single_work">
						<img src="assets/images/21.JPG" alt="" />
					</div>
					<p>언니가 들려주는 자위 후기~</p>
				</div>
				<div class="single_work_colum col-md-3 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="3s">
					<div class="single_work">
						<img src="assets/images/22.JPG" alt="" />
					</div>
					<p>혼자서 밤에 홍콩 가 본 후기</p>
				</div>
				<div class="single_work_colum col-md-3 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="4s">
					<div class="single_work">
						<img src="assets/images/23.JPG" alt="" />
					</div>
					<p>눈이 번쩍!!!</p>
				</div>
				
				<div class="btn_bg wow fadeInLeft"  data-wow-duration="3s">
				<a href="" class="btn">load More</a>
				</div>
			</div>
        </section><!-- End of Features Section -->
		
		
		
     <!--   <section id="about" class="about">-->
     <!--       <div class="container">-->
     <!--           <div class="row">-->
					<!--<div class="col-md-6 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="2s">-->
					<!--	<div class="head_title text-center">-->
					<!--		<h2>About me</h2>-->
					<!--		<div class="separator"></div>-->
					<!--	</div>-->
					<!--</div>-->
					<!--<div class="col-md-6 col-sm-6 col-xs-12 wow fadeInRight"  data-wow-duration="2s">-->
					<!--	<div class="head_title_rigth">-->
					<!--		<p>Fingerstache green juice semiotics quinoa, truffaut letterpress wolf photo booth ugh biodiesel mumblecore brunch. Meh austin vinyl banh mi, gluten-free chillwave scenester kombucha street art. Before they sold out lumbersexual chillwave, cold-pressed mumblecore beard pickled letterpress normcore crucifix.</p>-->
					<!--	</div>-->
					<!--</div>-->
     <!--               <div class="main_about_content text-center">-->
     <!--                  <div class="col-md-4 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="1.5s">-->
					<!--		<div class="single_about">-->
					<!--			<div class="single_about_img">-->
					<!--				<img src="assets/images/skil1.png" alt="" />-->
					<!--			</div>-->
					<!--			<h3><span class="statistic-counter">30.25</span>Curabitur</h3>-->
					<!--			<p>Four dollar toast messenger bag green juice, organic cliche tofu synth small batch locavore austin. Squid mlkshk authe ntic pinterest, pour-over gastropub XOXO seitan sartorial humblebrag. </p>-->
					<!--		</div>-->
					<!--	</div>-->
						
     <!--                  <div class="col-md-4 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="2s">-->
					<!--		<div class="single_about">-->
					<!--			<div class="single_about_img">-->
					<!--				<img src="assets/images/skil1.png" alt="" />-->
					<!--			</div>-->
					<!--			<h3><span class="statistic-counter">20.75</span>spanCurabitur</h3>-->
					<!--			<p>Four dollar toast messenger bag green juice, organic cliche tofu synth small batch locavore austin. Squid mlkshk authe ntic pinterest, pour-over gastropub XOXO seitan sartorial humblebrag. </p>-->
					<!--		</div>-->
					<!--	</div>-->
						
     <!--                  <div class="col-md-4 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="3s">-->
					<!--		<div class="single_about">-->
					<!--			<div class="single_about_img">-->
					<!--				<img src="assets/images/skil1.png" alt="" />-->
					<!--			</div>-->
					<!--			<h3><span class="statistic-counter">15.20</span>Curabitur</h3>-->
					<!--			<p>Four dollar toast messenger bag green juice, organic cliche tofu synth small batch locavore austin. Squid mlkshk authe ntic pinterest, pour-over gastropub XOXO seitan sartorial humblebrag. </p>-->
					<!--		</div>-->
					<!--	</div> -->
     <!--               </div>-->
     <!--           </div>-->
     <!--       </div>-->
     <!--   </section><!-- End of Features Section -->-->

       





        <section id="contact" class="contact">
            <div class="container">
                <div class="row">
                    <div class="main_contact">
                        
                        <div class="contact_content">
                            
                            <div class="col-md-6 col-sm-6 col-xs-12 wow fadeInLeft"  data-wow-duration="2s">
								<div class="contact_message">
									<form action="#" id="formid">
										<label for="">Name</label>
										<div class="form-group">
											<input type="text" class="form-control" name="name" placeholder="name" required="">
										</div>
										
										<label for="">Email</label>
										<div class="form-group">
											<input type="email" class="form-control" name="email" placeholder="Email" required="">
										</div>

										<label for="">Message</label>
										<div class="form-group">
											<textarea class="form-control" name="message" rows="8" placeholder="Message"></textarea>
										</div>

										<div class="message_btn text-center">
											<div class="btn_bg">
												<a href="" class="btn">Send</a>
											</div>
										</div>
									</form>
								</div>
							</div>

                            <div class="col-md-6 col-sm-6 col-xs-12 wow fadeInRight"  data-wow-duration="2s">
								<div class="contact_socail_bookmark_area">
									<div class="head_title text-center">
										<h2>GET IN TOUCH</h2>
										<div class="separator"></div>
									</div>
									
									
									<div class="contact_socail_bookmark">
										<a href=""><img src="assets/images/fb.png" alt="" /></a>
										<a href=""><img src="assets/images/fb.png" alt="" /></a>
										<a href=""><img src="assets/images/fb.png" alt="" /></a>
										<a href=""><img src="assets/images/fb.png" alt="" /></a>
										<a href=""><img src="assets/images/fb.png" alt="" /></a>
									</div>
									
									<div class="contact_adress">
										<h3>Address:</h3>
										<span>Seoul Young-San-Gu</span>
										<span>Chung-Pa 47 street 100</span>
									</div>
									
									<div class="row">
										<div class="col-md-6 col-sm-6 col-xs-12">
											<div class="single_contact_phone">
												<h3>Phone:</h3>
												<span>+82 010 - 0000 - 1004</span>
											</div>
										</div>
										
										<div class="col-md-6 col-sm-6 col-xs-12">
											<div class="single_contact_phone">
												<h3>Email:</h3>
												<span>women@sm.co.kr</span>
											</div>
										</div>
									</div>
									
								</div>
							</div>
                        </div>
                    </div>
                </div>
				
				<div class="row">
					<div class="footer_copyright">
					
						<div class="col-md-6 col-sm-6 col-xs-12 wow fadeInDown"  data-wow-duration="3s">
							<div class="single_copyirgth text-left">
								<p>Copyright 2017 &copy; by women@sm.ac.kr</p>
							</div>
						</div>
						
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="single_copyirgth wow fadeInUp"  data-wow-duration="2s">
								<ul class="navbar-right">
									<li class="active"><a href="#home">Home</a></li>
									<li><a href="#whatido">About</a></li>
									<li><a href="#myworks">How to masturbation</a></li>
									<li><a href="#about">Postscripts</a></li>
									<li><a href="#contact">Contact</a></li>
								</ul>
							</div>
						</div>
						
					</div>
				</div>
            </div>
        </section><!-- End of contact With Map Section -->

 

app/views/posts/_form.html.erb
<br><br><br><br>
<a href="/">돌아가기</a>

<%=form_for @post do |post_form|%>
  <div class="form-group">
    <div class="input-group">
      <span class="input-group-addon" id="basic-addon1">제목</span>
      <%= post_form.text_field :title, class: 'form-control', placeholder: '제목을 입력해주세요'%>
    </div>
    <br><br>
    <div class="input-group">
      <span class="input-group-addon" id="basic-addon1">내용</span>
        <%= post_form.text_area :content, class: 'form-control', placeholder: '내용을 입력해주세요'%>
    </div>    

  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <%= post_form.file_field :image %>
  </div>


    <br><br><%= post_form.submit "등록", class: 'btn btn-default'%>

<%end%>

app/views/posts/index.html.erb
<br><br><br><br>
<% @posts.each do |post| %>
    분류: <%=post.category %>
    제목: <%=post.title %>
    내용: <%=post.content %>
<% end %>

<%=link_to "새로운 글쓰기", new_post_path %>
qwegqweg

app/views/posts/new.html.erb
    <%= render partial: 'form' %>

<%= link_to 'Back', '/board' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>